### PR TITLE
Added support for nicknamed users in object arrays.

### PR DESCRIPTION
**Pull request by GamingAndStuffs**
Before, nicknamed users would show up as just strings if you get an object array from a command. This just removes the `!` present in the mention tag before checking the regex.

### CODE REVIEW

**Comment by BtoBastian** [comment]
Thank you!
Is this tested? I can see some issues with the .substring() call in the next line.

**Comment by GamingAndStuffs** [comment]
Whoops. It should be fixed now, and I actually tested it this time.

**Comment by GamingAndStuffs** [comment]
Oh hey, cool unintentional commit there @me.

**Comment by BtoBastian** [comment]
cool

**Pull request closed without merging**
